#!/usr/bin/env python3
"""
Auto-update .kata-catalog.yaml with current statistics.
This script scans the katas/ directory and updates the catalog metadata.
"""

import yaml
from pathlib import Path
from datetime import datetime, UTC
from collections import Counter


def find_all_katas(katas_dir: Path) -> list[dict]:
    """Find all kata.yaml files and parse them."""
    katas = []

    for kata_dir in katas_dir.iterdir():
        if not kata_dir.is_dir():
            continue

        kata_yaml = kata_dir / "kata.yaml"
        steps_md = kata_dir / "steps.md"

        if kata_yaml.exists() and steps_md.exists():
            try:
                with open(kata_yaml, 'r', encoding='utf-8') as f:
                    kata_data = yaml.safe_load(f)
                    katas.append(kata_data)
            except Exception as e:
                print(f"Warning: Failed to parse {kata_yaml}: {e}")
                continue

    return katas


def calculate_stats(katas: list[dict]) -> dict:
    """Calculate catalog statistics from kata list."""
    total = len(katas)

    # Count by level
    levels = Counter(kata.get('level', 'unknown') for kata in katas)

    # Count by status
    statuses = Counter(kata.get('status', 'draft') for kata in katas)

    return {
        'total_katas': total,
        'last_updated': datetime.now(UTC).strftime('%Y-%m-%dT%H:%M:%SZ'),
        'by_level': {
            'beginner': levels.get('beginner', 0),
            'intermediate': levels.get('intermediate', 0),
            'advanced': levels.get('advanced', 0),
        },
        'by_status': {
            'draft': statuses.get('draft', 0),
            'published': statuses.get('published', 0),
            'archived': statuses.get('archived', 0),
        }
    }


def update_catalog_file(catalog_path: Path, katas: list[dict]):
    """Update .kata-catalog.yaml with current statistics."""

    # Load existing catalog
    with open(catalog_path, 'r', encoding='utf-8') as f:
        catalog = yaml.safe_load(f)

    # Calculate new stats
    new_stats = calculate_stats(katas)

    # Update stats section
    catalog['stats'] = new_stats

    # Write back
    with open(catalog_path, 'w', encoding='utf-8') as f:
        # Add header comment
        f.write("# CodeMie Kata Catalog Configuration\n")
        f.write("# This file contains metadata about the entire kata catalog\n")
        f.write("# Statistics are auto-generated by scripts/update_catalog.py\n\n")

        yaml.dump(catalog, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    print(f"✅ Updated .kata-catalog.yaml")
    print(f"   Total katas: {new_stats['total_katas']}")
    print(f"   By level: {new_stats['by_level']}")
    print(f"   By status: {new_stats['by_status']}")
    print(f"   Last updated: {new_stats['last_updated']}")


def main():
    """Main function."""
    # Find repository root
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent

    katas_dir = repo_root / "katas"
    catalog_path = repo_root / ".kata-catalog.yaml"

    if not katas_dir.exists():
        print(f"Error: Katas directory not found: {katas_dir}")
        return 1

    if not catalog_path.exists():
        print(f"Error: Catalog file not found: {catalog_path}")
        return 1

    # Find all katas
    katas = find_all_katas(katas_dir)

    if not katas:
        print("Warning: No katas found")
        return 0

    # Update catalog
    update_catalog_file(catalog_path, katas)

    return 0


if __name__ == "__main__":
    exit(main())
